[phases.setup]
nixpkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required for Node.js backend'"]

[start]
cmd = "npm start"
